### ISSUE TITLE
Comments not working (action "newAction" does not exist in controller)

### ISSUE THREAD

**Issue by HorstBaumann** [midhundevasia/typo3-blogmaster#2]
GREAT EXTENSION !!!
It seems to be much more comfortable than all other blog-extensions,
but one little bug keeps me from using it ... :'-(

I'm not able to generate any comment.
neither in the FrontEnd nor in the BackEnd

Uncaught TYPO3 Exception
#1186669086: An action "newAction" does not exist in controller "Tutorboy\Blogmaster\Controller\CommentController". (More information)

TYPO3\CMS\Extbase\Mvc\Exception\NoSuchActionException thrown in file
........../typo3_src-7.6.12/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php in line 258.

TYPO3 7.6.12
blogmaster 1.0.5

**Comment by midhundevasia** [comment]
Hi @HorstBaumann 
Thank you for your comment.  😄 

1. The backend comment creation bug has been fixed, and it will be available from next release `1.0.6`.
2. Frontend Comment Form is working fine in all versions. (I think you forgot to add the Blog Comment Plugin just below the Blog -> Detail View plugin page). Otherwise, you don't get the comment submissions. Please make sure that you did the settings as shown in the screen below.

<img width="903" alt="blog comment plugin" src="https://cloud.githubusercontent.com/assets/197399/20723724/a6e898ca-b691-11e6-844e-53bdd033b1e7.png">
<img width="933" alt="backend single page" src="https://cloud.githubusercontent.com/assets/197399/20723725/a6ed8a06-b691-11e6-946c-6a202cce5716.png">



Regards,
Midhun Devasia

**Comment by HorstBaumann** [comment]
IT WORKS ! :-)

thanks a lot for your quick response and your phantastic work!
now I can set up my first blogmaster :-)

**Comment by HorstBaumann** [comment]
Is it correct - there's no confirmation message, after comment submit?

I guess you're still working on the whole comment-management ...?
Approval/Spam/etc. (an important feature would be, to set all new comments to "unapproved" by default - but as I can see, you planned it - perfect)
So, I'm looking forward for 1.0.6 :-)

Best Regards
Frank

**Comment by midhundevasia** [comment]
Hi @HorstBaumann 

Yes, there is not confirmation message after comment submits, it will try to include that in next release. 

And the Default comment status is already there, I missed that in the documentation. You can use 
`defaultCommentStatus` in the TypoScript settings `defaultCommentStatus = pending`. Possible values are `publish`, `pending`, `spam`.

Yes, you are correct, am working on the comment features and bugs fixes more in `1.0.6`.

Regards,
Midhun Devasia

**Comment by midhundevasia** [comment]
Fixed in 1.0.6
